#!/bin/bash
# exit when any command fails
set -e
#################################################################



export SCRIPTDIR=$( dirname $0 )
export UTILS=${SCRIPTDIR}/utils
export FLYPOL=${UTILS}/flyePolish
export FISHPOL=${UTILS}/medakaPolish
export RACOONPOL=${UTILS}/raconPolish
export CHIMERAPOL=${UTILS}/chimeraPolish
export PATH=${UTILS}:${PATH}


source ${UTILS}/versions.txt
source ${UTILS}/helper-functions.txt
source ${UTILS}/defaults.txt


#########################################################################################################
## VERSION CATCH
#########################################################################################################
version_check ${@}


#########################################################################################################
## HELP: CATCH NO ARGS or ERROR WITH FIRST ARG
#########################################################################################################
help_catch ${@}

#########################################################################################################
## FIND DEPENDENCIES
#########################################################################################################
# This can be done in each script as needed....
#export MM2=$( which minimap2 )
#export FLYE=$( which flye )
#export RACON=$( which racon )
#export MEDAKA=$( which medaka_consensus )
#export SAMTOOLS=$( which samtools )
#export PY3=$( which python3 )
#for VAR in MM2 FLYE RACON MEDAKA SAMTOOLS PIPELINE DO_FLYE_PIPELINE DO_RACOON_PIPELINE DO_FISH_PIPELINE DO_CHIMERA_PIPELINE ; do echo -e "${VAR}\t${!VAR}" ; done




#########################################################################################################
## SAVE ALL QC CHECKS FOR PIPELINES
#########################################################################################################
${RUN} ${@:2}

