#!/bin/bash
set -e
#################################################################
#conda activate medaka
#conda activate medakaOct2022


## Collecting some VARs
export SCRIPTNAME=$( basename ${0} )
export SUBSCRIPTDIR=$( dirname ${0} )
if [ -z ${UTILS} ]; then export UTILS=$( dirname ${0} ) ; fi	## should be same as SUBSCRIPT DIR ; if running racoonFlyFish, it will already be in ENV, else it will be taken from versions.txt
export PATH=${UTILS}:${PATH}					## To be sure ; and especially when this script run directly.

## Early source needs
source ${UTILS}/versions.txt
source ${UTILS}/helper-functions.txt



## VERSION MESSAGE
version_check ${@}


## HELP
if [ $# -eq 0 ]; then fishhelp ; exit ; fi





##############################################################################
## REQUIRED
##############################################################################
export FOFN=""
export READS=""
export MODEL=""		## r941_min_sup_g507

##############################################################################
## DEFAULTS
##############################################################################
export SCRIPTDIR=${SCRIPTDIR}	## Empty if using this script directly, i.e. not using racoonFlyFish

export THREADS=16
export P=${THREADS}

export MEDAKAROUNDS=1
export ITERS=${MEDAKAROUNDS}
export ROUNDS=${MEDAKAROUNDS}

export MAINWD=${PWD}
export SLURM=false      ## if true, THREADS or P also used for NTASKS
export TIME=24:00:00    ## SLURM option
export MEM=100G          ## SLURM option


export ALLVARS=""

export MEDAKA=$( which medaka_consensus )
export MM2=$( which minimap2 )
export MINMAP2=$( which minimap2 )


export DEBUG=true
export CONTINUE=true
export HELP=false
export VERBOSE=false
export MEDAKAHELP=false


##############################################################################
## GET OPTS
##############################################################################
while getopts "i:R:t:r:ST:M:m:Hv" arg; do
    case $arg in
        i) export FOFN=${OPTARG} ; FOFNMODE=true ;;
        R) export READS=${OPTARG} ;;
        t) export THREADS=${OPTARG} ; export P=${THREADS} ;;
        r) export ROUNDS=${OPTARG} ; export ITERS=${OPTARG} ; export MEDAKAROUNDS=${OPTARG} ;;
        S) export SLURM=true ;;
        T) export TIME=${OPTARG} ;;
        M) export MEM=${OPTARG} ;;
        m) export MODEL=${OPTARG} ;;
        H) export MEDAKAHELP=true ;;
        v) export VERBOSE=true ;;
        *) help; exit;;
    esac
done




##############################################################################
## PROCESSING ARGS
##############################################################################
if [ -z ${MEDAKA} ]; then echo "medaka_consensus not found in PATH. Please add it to PATH. Exiting..." ; echo ; fishhelp ; exit ; fi
if [ -z ${MM2} ]; then echo "minimap2 not found in PATH. Please add it to PATH. Exiting..." ; echo ; fishhelp ; exit ; fi
if $MEDAKAHELP ; then medaka --version ; medaka_consensus --h ; fi

for REQUIRED in FOFN READS MODEL  ; do echo -e "REQUIRED\t${REQUIRED}\t${!REQUIRED}" ; if [ -z ${!REQUIRED} ]; then echo ${REQUIRED} is a required argument. Not given. Exiting. ; echo ; fishhelp ; fi ; done
for ARG in ROUNDS THREADS SLURM TIME MEM ; do echo -e "OPTIONS\t${ARG}\t${!ARG}" ; done




##############################################################################
## EXECUTE
##############################################################################
medaka_polish_loop

exit

