#!/bin/bash
set -e
#################################################################
#source ~/.bash_profile
#source ~/software/conda/source-conda-for-scripts.sh
#conda activate miniasm


## Collecting some VARs
export SCRIPTNAME=$( basename ${0} )
export SUBSCRIPTDIR=$( dirname ${0} )
if [ -z ${UTILS} ]; then export UTILS=$( dirname ${0} ) ; fi	## should be same as SUBSCRIPT DIR ; if running racoonFlyFish, it will already be in ENV, else it will be taken from versions.txt
export PATH=${UTILS}:${PATH}					## To be sure ; and especially when this script run directly.

## Early source needs
source ${UTILS}/versions.txt
source ${UTILS}/helper-functions.txt



## VERSION MESSAGE
version_check ${@}


## HELP
if [ $# -eq 0 ]; then racoonhelp ; exit ; fi




##############################################################################
## REQUIRED
##############################################################################
export FOFN=""
export READS=""
export X=""	#map-ont map-pb

##############################################################################
## DEFAULTS
##############################################################################
export SCRIPTDIR=${SCRIPTDIR}	## Empty if using this script directly, i.e. not using racoonFlyFish


export THREADS=16
export P=${THREADS}

export RACONROUNDS=4
export ITERS=${RACONROUNDS}
export ROUNDS=${RACONROUNDS}

export MAINWD=${PWD}
export SLURM=false      ## if true, THREADS or P also used for NTASKS
export TIME=12:00:00    ## SLURM option
export MEM=80G          ## SLURM option

export MM2=$( which minimap2 )
export MINIMAP2=$( which minimap2 )
export RACON=$( which racon )

export ALLVARS=""
export P=16
export MEM=24G
export TIME=8:00:00

export DEBUG=true
export CONTINUE=true
export HELP=false
export VERBOSE=false
export RACONHELP=false


##############################################################################
## GET OPTS
##############################################################################
while getopts "i:R:t:r:ST:M:x:Hv" arg; do
    case $arg in
        i) export FOFN=${OPTARG} ; FOFNMODE=true ;;
        R) export READS=${OPTARG} ;;
        t) export THREADS=${OPTARG} ; export P=${THREADS} ;;
        r) export ROUNDS=${OPTARG} ; export ITERS=${OPTARG} ; export RACONROUNDS=${OPTARG} ;;
        S) export SLURM=true ;;
        T) export TIME=${OPTARG} ;;
        M) export MEM=${OPTARG} ;;
        x) export X=${OPTARG} ;;
        H) export RACONHELP=true ;;
        v) export VERBOSE=true ;;
        *) help; exit;;
    esac
done




##############################################################################
## PROCESSING ARGS
##############################################################################
for REQUIRED in RACON MINIMAP2 ; do if [ -z ${REQUIRED} ]; then echo "${REQUIRED} not found in PATH. Please add it to PATH. Exiting..." ; echo ; racoonhelp ; exit ; fi ; done
if $RACONHELP ; then racon --version ; racon --help ; fi

for REQUIRED in FOFN READS X ; do echo -e "REQUIRED\t${REQUIRED}\t${!REQUIRED}" ; if [ -z ${!REQUIRED} ]; then echo ${REQUIRED} is a required argument. Not given. Exiting. ; echo ; racoonhelp ; exit; fi ; done
for ARG in ROUNDS THREADS SLURM TIME MEM ; do echo -e "OPTIONS\t${ARG}\t${!ARG}" ; done




##############################################################################
## EXECUTE
##############################################################################
racon_polish_loop

exit



